<?php

/**
 * @file
 * Custom module for small, utility-type routines.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function uwmed_clockwise_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  if ($entity->getType() === "uwm_clinic") {

    if ($entity->field_clockwise_id->value) {

      $values = [
        'nid' => $entity->nid->value,
        'clockwise_id' => $entity->field_clockwise_id->value,
        'wait_snippet' => $entity->field_clinic_wait_time_snippet->value,
      ];
      $build['#attached']['drupalSettings']['uwmed_clockwise']['clinics'] = $values;

    }

  }

}

/**
 * Implements hook_preprocess_field().
 */
function uwmed_clockwise_preprocess_field(&$variables, $hook) {

  $element = $variables['element'];
  $variables['classes_array'][] = 'aClassName';

  if ($element['#field_name'] == 'field_clockwise_id' ||
      $element['#field_name'] == 'field_clinic_wait_time_snippet'
  ) {

    $values = [
      'nid' => $variables['element']['#object']->nid->value,
      'clockwise_id' => $variables['element']['#object']->field_clockwise_id->value,
      'wait_snippet' => $variables['element']['#object']->field_clinic_wait_time_snippet->value,
    ];

    $variables['#attached']['drupalSettings']['uwmed_clockwise2']['clinics'][] = $values;

  }

}
