#!/usr/bin/env bash

set -ev

blt frontend --site=default
blt frontend --site=chew

blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_TAG}" --tag "${TRAVIS_TAG}-build" --ignore-dirty --verbose

set +v
