#!/usr/bin/env bash

set -ev

blt frontend -D site=default
blt frontend -D site=chew

blt deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_TAG}" --tag "${TRAVIS_TAG}-build" --ignore-dirty -v

set +v
