#!/usr/bin/env bash

set -ev

openssl aes-256-cbc -K $encrypted_02aeaa5f32a9_key -iv $encrypted_02aeaa5f32a9_iv -in travis-deploy-key.enc -out travis-deploy-key -d
rm travis-deploy-key.enc
chmod 600 travis-deploy-key
mv travis-deploy-key ~/.ssh/id_rsa

set +v
