project:
  machine_name: uwmed
  prefix: UWM
  human_name: 'UW Medicine'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: '${project.machine_name}.local'
git:
  default_branch: develop
  remotes:
    - 'uwmed@svn-23450.prod.hosting.acquia.com:uwmed.git'
  hooks:
    pre-commit: '${repo.root}/git-config/hooks'
    commit-msg: '${repo.root}/git-config/hooks'
disable-targets:
  validate:
      twig: true
validate:
  twig:
    filesets:
      - files.twig.null.custom
drush:
  aliases:
    remote: '${project.machine_name}.dev'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield, simplesamlphp_auth]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
target-hooks:
  frontend-setup:
    dir: '${docroot}'
    command: 'echo ''No frontend-setup configured.'''
  frontend-build:
    dir: '${docroot}'
    command: 'echo ''No frontend-build configured.'''
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${deploy.dir}/docroot'
    command: 'echo ''No post-deploy build configured.'''
  post-setup-build:
    dir: '${docroot}'
    command: 'echo ''No post-setup build configured.'''
  post-deploy:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
multisites:
  - default
  - chew
  - huddle
  - calendar
behat:
  web-driver: selenium
vm:
  enable: true
cm.allow-overrides: true
