<?php

/**
 * @file
 * General functionality and hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_view().
 */
function uwmcms_chew_views_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'related_articles') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node) {
      if (!empty($node->field_categories)) {
        $category = $node->field_categories->entity;
        if (isset($category)) {
          // Use the parent term if one exists.
          $parents = \Drupal::entityTypeManager()
            ->getStorage('taxonomy_term')
            ->loadParents($category->id());

          if (empty($parents)) {
            $args[0] = $category->id();
          }
          else {
            $parent = array_shift($parents);
            $args[0] = $parent->id();
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for Views exposed filter forms.
 */
function uwmcms_chew_views_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $storage = $form_state->getStorage();
  $view = $storage['view'];

  if ($view->id() == 'search_articles' && $view->current_display == 'page') {
    // Move the actions before the search input field.
    $form['search']['#weight'] = 20;
    $form['actions']['#weight'] = 10;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for Page 1.
 *
 * Hide certain action options and alter text of others.
 */
function uwmcms_chew_views_form_views_form_articles_admin_page_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['header']['node_bulk_form']['action'])) {
    return;
  }

  if (isset($form['header']['node_bulk_form']['action']['#options']['node_delete_action'])) {
    unset($form['header']['node_bulk_form']['action']['#options']['node_delete_action']);
  }
  if (isset($form['header']['node_bulk_form']['action']['#options']['node_make_sticky_action'])) {
    $form['header']['node_bulk_form']['action']['#options']['node_make_sticky_action'] = 'Make highlighted';
  }
  if (isset($form['header']['node_bulk_form']['action']['#options']['node_make_unsticky_action'])) {
    $form['header']['node_bulk_form']['action']['#options']['node_make_unsticky_action'] = 'Make unhighlighted';
  }
  if (isset($form['header']['node_bulk_form']['action']['#options']['node_promote_action'])) {
    $form['header']['node_bulk_form']['action']['#options']['node_promote_action'] = 'Make featured';
  }
  if (isset($form['header']['node_bulk_form']['action']['#options']['node_unpromote_action'])) {
    $form['header']['node_bulk_form']['action']['#options']['node_unpromote_action'] = 'Make unfeatured';
  }
  if (isset($form['header']['node_bulk_form']['action']['#options']['node_save_action'])) {
    unset($form['header']['node_bulk_form']['action']['#options']['node_save_action']);
  }
  if (isset($form['header']['node_bulk_form']['action']['#options']['pathauto_update_alias_node'])) {
    unset($form['header']['node_bulk_form']['action']['#options']['pathauto_update_alias_node']);
  }
}
