<?php

/**
 * @file
 * General functionality and hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_view().
 */
function uwmcms_chew_views_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'related_articles') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node) {
      if (!empty($node->field_categories)) {
        $category = $node->field_categories->entity;
        if (isset($category)) {
          // Use the parent term if one exists.
          $parents = \Drupal::entityTypeManager()
            ->getStorage('taxonomy_term')
            ->loadParents($category->id());

          if (empty($parents)) {
            $args[0] = $category->id();
          }
          else {
            $parent = array_shift($parents);
            $args[0] = $parent->id();
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for Views exposed filter forms.
 */
function uwmcms_chew_views_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $storage = $form_state->getStorage();
  $view = $storage['view'];

  if ($view->id() == 'search_articles' && $view->current_display == 'page') {
    // Move the actions before the search input field.
    $form['search']['#weight'] = 20;
    $form['actions']['#weight'] = 10;
  }
}
