<?php

/**
 * @file
 * General functionality and hook implementations.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_view().
 */
function uwmcms_chew_views_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'related_articles') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node) {
      $category = $node->field_categories->entity;
      $args[0] = $category->id();

      /* In case the articles need to be selected by parent term again.
      $parents = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadParents($category->id());
      if (empty($parents)) {
        $args[0] = $category->id();
      }
      else {
        $parent = array_shift($parents);
        $args[0] = $parent->id();
      }
      */
    }
  }
}
