<?php

/**
 * @file
 * Custom module for small, utility-type routines.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function uwmcs_utils_menu_link_content_presave(EntityInterface $entity) {

  // Set new menu links to show as expanded by default
  // if ($entity->menu_name->value == 'main') {.
  $entity->expanded = 1;

}

/**
 * Implements hook_page_attachments().
 */
function uwmcs_utils_page_attachments(array &$attachments) {

  $admin_context = \Drupal::service('router.admin_context');
  if ($admin_context->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'uwmcs_utils/admin-pages-css';
  }

}

/**
 * Implements hook_entity_field_access().
 */
function uwmcs_utils_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {

  $allowedFields = [
    'field_clockwise_id',
    'field_clinic_wait_time_snippet',
    'title',
  ];

  $account = \Drupal::currentUser();
  if ($operation === 'edit' &&
      in_array('staff_clinic_manager', $account->getRoles())) {

    if (in_array($field_definition->getName(), $allowedFields)) {

      return AccessResult::neutral();
    }

    return AccessResult::forbidden();
  }

  return AccessResult::neutral();

}

/**
 * Implements hook_views_pre_view().
 */
function uwmcs_utils_views_pre_view(ViewExecutable $view, $display_id, array &$args) {

  if ($view->id() == 'clinic_hours') {
    // $args[0] = '4566';.
  }

}
