<?php

/**
 * @file
 * Module for reading an API and providing API data to themes.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uwmcs_reader_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.uwmcs_reader':
      return t('
        <h2>UWMCS JSON Reader generator for Drupal.</h2>
        <h3>Instructions</h3>
        <p>UWMCS JSON Reader dolor sit amet... <strong>Just kidding!</strong></p>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/uwmcs_reader</strong> and enter your own set of phrases to build random-generated text (or go with the default UWMCS JSON Reader).</p>
        <p>Last, visit <strong>www.example.com/uwmcs_reader/generate/P/S</strong> where:</p>
        <ul>
          <li><em>P</em> is the number of <em>paragraphs</em></li>
          <li><em>S</em> is the maximum number of <em>sentences</em></li>
        </ul>
        <p>There is also a generator block in which you can choose how many paragraphs and
phrases and it\'ll do the rest.</p>
        <p>If you need, there\'s also a specific <em>generate uwmcs reader</em> permission.</p>
        <h3>Attention</h3>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions, ok?</p>
      ');
  }
}
