definitions:
  contact__site_page:
    weight: -50
    menu_name: footer
    parent: ''
    enabled: true
    expanded: false
  node__add__award:
    weight: 1
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  node__add__page:
    weight: 2
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  node__add__campaign:
    weight: 3
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  node__add__event:
    weight: 4
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  node__add__gallery:
    weight: 5
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  node__add__landing_page:
    weight: 6
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  node__add__question:
    weight: 8
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  node__add__webform:
    weight: 9
    menu_name: admin
    parent: node.add_page
    expanded: false
    enabled: true
  entity__block_content_type__edit_form__basic:
    weight: 4
    menu_name: admin
    parent: entity.block_content_type.collection
    expanded: false
    enabled: true
  entity__block_content_type__edit_form__disqus_comments:
    weight: 6
    menu_name: admin
    parent: entity.block_content_type.collection
    expanded: false
    enabled: true
  entity__block_content_type__edit_form__poll_block_and_save:
    weight: 7
    menu_name: admin
    parent: entity.block_content_type.collection
    expanded: false
    enabled: true
  entity__block_content_type__edit_form__promotional:
    weight: 8
    menu_name: admin
    parent: entity.block_content_type.collection
    expanded: false
    enabled: true
  entity__menu__edit_form__admin:
    weight: -49
    menu_name: admin
    parent: entity.menu.collection
    expanded: false
    enabled: true
  entity__menu__add_link_form__admin:
    weight: 4
    menu_name: admin
    parent: entity.menu.edit_form.admin
    expanded: false
    enabled: true
  entity__menu__edit_form__footer:
    weight: -43
    menu_name: admin
    parent: entity.menu.collection
    expanded: false
    enabled: true
  entity__menu__edit_form__header-menu:
    weight: -44
    menu_name: admin
    parent: entity.menu.collection
    expanded: false
    enabled: false
  entity__menu__edit_form__main:
    weight: -47
    menu_name: admin
    parent: entity.menu.collection
    expanded: false
    enabled: true
  entity__menu__edit_form__tools:
    weight: -42
    menu_name: admin
    parent: entity.menu.collection
    expanded: false
    enabled: true
  entity__menu__edit_form__account:
    weight: -41
    menu_name: admin
    parent: entity.menu.collection
    expanded: false
    enabled: true
  entity__block_content_type__delete_form__basic:
    weight: 8
    menu_name: admin
    parent: entity.block_content_type.edit_form.basic
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
