acquia_connector: 1.14.0
acquia_contenthub: 1.30.0
acquia_contenthub_diagnostic: 1.30.0
acquia_contenthub_subscriber: 1.30.0
acquia_lift: 3.8.0
acquia_lift_inspector: 3.8.0
acquia_purge: 1.0.0-beta3
address: 1.4.0
admin_toolbar: 1.24.0
admin_toolbar_tools: 1.24.0
adminimal_admin_toolbar: 1.8.0
allowed_formats: 1.1.0
better_exposed_filters: 3.0.0-alpha4
block: 8.4.5
block_content: 8.4.5
breakpoint: 8.4.5
ckeditor: 8.4.5
conditional_fields: 1.0.0-alpha4
config: 8.4.5
config_filter: 1.2.0
config_ignore: 2.1.0
config_update: 1.5.0
contact: 8.4.5
contact_storage: 1.0.0-beta9
content_moderation: 8.4.5
contextual: 8.4.5
crop: 2.0.0-beta1
ctools: 3.0.0
ctools_block: 3.0.0
datetime: 8.4.5
devel: 1.2.0
diff: 1.0.0-rc1
disqus: 1.0.0-rc3
duration_field: 1.6.0
dynamic_page_cache: 8.4.5
editor: 8.4.5
editor_advanced_link: 1.4.0
embed: 1.0.0
entity: 1.0.0-beta1
entity_block: 1.0.0-alpha2
entity_browser: 2.0.0-alpha2
entity_embed: 1.0.0-beta2
entity_reference: 8.4.5
entity_reference_revisions: 1.5.0
features: 3.8.0
field: 8.4.5
field_group: 1.0.0
field_ui: 8.4.5
file: 8.4.5
filter: 8.4.5
focal_point: 1.0.0-beta6
google_tag: 0.0.0
help: 8.4.5
history: 8.4.5
honeypot: 1.29.0
image: 8.4.5
inline_entity_form: 1.0.0-beta1
layout_discovery: 8.4.5
lightning_contact_form: 1.0.0-rc2
lightning_core: 1.0.0-rc2
lightning_media: 1.0.0-rc3
lightning_media_document: 1.0.0-rc3
lightning_media_image: 1.0.0-rc3
lightning_media_instagram: 1.0.0-rc3
lightning_media_twitter: 1.0.0-rc3
lightning_media_video: 1.0.0-rc3
lightning_page: 1.0.0-rc2
lightning_scheduler: 1.0.0-rc2
link: 8.4.5
link_attributes: 1.5.0
media: 8.4.5
media_entity_actions: 1.0.0-alpha2
media_entity_instagram: 2.0.0-alpha1
media_entity_twitter: 2.0.0-alpha2
memcache: 2.0.0-rc1
menu_ui: 8.4.5
metatag: 1.4.0
metatag_facebook: 1.4.0
metatag_open_graph: 1.4.0
metatag_twitter_cards: 1.4.0
node: 8.4.5
options: 8.4.5
page_cache: 8.4.5
paragraphs: 1.2.0
path: 8.4.5
poll: 1.2.0
purge: 3.0.0-beta8
purge_drush: 3.0.0-beta8
purge_processor_cron: 3.0.0-beta8
purge_processor_lateruntime: 3.0.0-beta8
purge_queuer_coretags: 3.0.0-beta8
purge_ui: 3.0.0-beta8
responsive_favicons: 1.4.0
rest: 8.4.5
robotstxt: 1.2.0
search: 8.4.5
seckit: 1.0.0
serialization: 8.4.5
sharethis: 0.0.0
shortcut: 8.4.5
syslog: 8.4.5
system: 8.4.5
taxonomy: 8.4.5
telephone: 8.4.5
text: 8.4.5
token: 1.1.0
toolbar: 8.4.5
twig_tweak: 1.9.0
user: 8.4.5
video_embed_field: 2.0.0-alpha2
video_embed_media: 2.0.0-alpha2
video_embed_wysiwyg: 2.0.0-alpha2
views_infinite_scroll: 1.5.0
views_ui: 8.4.5
webform: 5.0.0-rc3
webform_node: 5.0.0-rc3
webform_ui: 5.0.0-rc3
workflows: 8.4.5
contribute: 1.0.0-beta7
menu_link_content: 8.4.5
pathauto: 1.0.0
views: 8.4.5
lightning: 3.003.0
media_library: 8.6.2
config_split: 1.4.0
