<?php

/**
 * @file
 * General functionality and hook implementations.
 */

use Facebook\InstantArticles\Transformer\Rules\PullquoteCiteRule;
use Facebook\InstantArticles\Transformer\Rules\PullquoteRule;

/**
 * Implements hook_fb_instant_articles_transformer_rules_alter().
 */
function uwmcms_chew_fbia_fb_instant_articles_transformer_rules_alter(array &$rules) {
  $rules[] = [
    'class' => PullquoteRule::class,
    'selector' => 'aside',
  ];
  $rules[] = [
    'class' => PullquoteCiteRule::class,
    'selector' => 'cite',
  ];
}
