<?php

/**
 * @file
 * Module for reading an API and providing API data to themes.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\uwmcs_reader\Controller\UwmFetcher;

/**
 * Implements hook_node_view().
 *
 * @TODO: Change this to node_load().
 */
function uwmcs_reader_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  $args = explode('/', trim(
    \Drupal::request()->getRequestUri(), '/'));

  if ($entity->getType() === "uwm_clinic") {

    // Fetch Information Manager (IM) data from API endpoint.
    $fetcher = new UwmFetcher();
    $data = $fetcher->getUrl($entity->field_information_manager_url->value);

    // If missing, try to find data by current url.
    if (empty((array) $data)) {
      $data = $fetcher->getClinic(['clinicUrl' => '/locations/' . $args[1]]);
    }

    // If clinic has location, fetch full location details.
    if (!empty($data->location->url)) {
      $location = $fetcher->getUrl($data->location->url);
      if (!empty($location->id)) {
        $data->location = $location;
      }
    }

    // If clinic has providers, populate full provider details.
    // @TODO: Change this attach bio-node.
    if (!empty($data->careNetworks)) {

      foreach ($data->careNetworks as &$network) {

        foreach ($network->bioInformations as &$bio) {

          if (!empty($bio->url)) {

            $detail = $fetcher->getUrl($bio->url);
            if (!empty($bio->id)) {
              $bio = $detail;
            }

          }

        }

      }

    }

    // If location has hours, get unix time for javascripts.
    $unixTime = function ($dayOfWeek, $timeOfDay, $useNext = FALSE) {
      $days = [
        'Sunday',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
      ];
      $day = $days[$dayOfWeek];
      list($hours, $minutes, $seconds) = explode(':', $timeOfDay);

      // PHP next is the following, not next week:
      $time = strtotime(($useNext ? "Next " : "") . $day);
      $time = strtotime("+ $hours hours", $time);
      $time = strtotime("+ $minutes minutes", $time);
      $time = strtotime("+ $seconds seconds", $time);

      return $time;

    };

    foreach ($data->clinicTimeUseMasters as &$collection) {

      $opens = $closes = $nextOpens = $nextCloses = [];
      foreach ($collection->hoursOfOperation as &$entry) {

        $opens[] = $unixTime($entry->dayOfWeek, $entry->startTime);
        $closes[] = $unixTime($entry->dayOfWeek, $entry->endTime);
        $nextOpens[] = $unixTime($entry->dayOfWeek, $entry->startTime, TRUE);
        $nextCloses[] = $unixTime($entry->dayOfWeek, $entry->endTime, TRUE);

      }

      $collection->opens = min($opens);
      $collection->closes = min($closes);
      $collection->nextOpens = min($nextOpens);
      $collection->nextCloses = min($nextCloses);

    }

    $entity->uwmcs_reader_api_values = $data;

  }

  if ($entity->getType() === "uwm_provider") {

    // Fetch Information Manager (IM) data from API.
    $fetcher = new UwmFetcher();
    $data = $fetcher->getUrl($entity->field_information_manager_url->value);

    // If missing, try to find clinic using current URL.
    if (empty((array) $data)) {
      $data = $fetcher->getProvider(['friendlyUrl' => $args[1]]);
    }

    // Fetch details for publications.
    if (!empty($data->bioPublications[0]->pubMedId)) {

      $pubIds = [];
      foreach ($data->bioPublications as $k => $v) {
        array_push($pubIds, $v->pubMedId);
      }

      $data->bioPublicationsDetails = $fetcher->getUrl(
        'https://webservices.uwmedicine.org/api/publications?ids=' .
        implode(',', $pubIds));

    }

    // If provider has clinics, populate full clinic details.
    // @TODO: Change this to node-load locations.
    if (!empty($data->careNetworks[0]->clinicBases)) {

      foreach ($data->careNetworks as &$network) {

        foreach ($network->clinicBases as &$clinic) {

          if (!empty($clinic->url)) {

            $detail = $fetcher->getUrl($clinic->url);
            if (!empty($clinic->id)) {
              $clinic = $detail;
            }

          }

        }

      }

    }

    $entity->uwmcs_reader_api_values = $data;
  }

  if ($entity->getType() === "uwm_medical_service") {

    // Fetch Information Manager (IM) data from API.
    $fetcher = new UwmFetcher();

    $urgent_care_data = $fetcher->getUrl('https://webservices.uwmedicine.org/api/medicalservice/60');
    if (!empty($urgent_care_data->clinics)) {
      $entity->uwmcms_reader_urgent_care_clinics = $urgent_care_data->clinics;
    }

    $primary_care_data = $fetcher->getUrl('https://webservices.uwmedicine.org/api/medicalservice/57');
    if (!empty($primary_care_data->clinics)) {
      $entity->uwmcms_reader_primary_care_clinics = $primary_care_data->clinics;
    }

    if (isset($entity->field_information_manager_url->value)) {
      $medical_service_data = $fetcher->getUrl($entity->field_information_manager_url->value);
      if (!empty($medical_service_data)) {
        $entity->uwmcms_reader_medical_service_clinics = $medical_service_data->clinics;
      }
    }

  }

}
